from . import abstract_person
from . import contact_person
from . import doctor_speciality
from . import hr_hospital_doctor
from . import hr_hospital_patient
from . import hr_hospital_disease
from . import medical_diagnosis
from . import hr_hospital_visit
from . import doctor_schedule
from . import patient_doctor_history
